name: healthcheck

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test (twice, if needed)
        run: make test || make test
      - name: Healthcheck ping
        run: wget https://healthchecks.home.mullie.eu/ping/1aaaf89a-fe3d-4a6f-a5b5-cec60205dc52 -T 10 -t 5 -O /dev/null
